# Generated by Django 4.1 on 2023-09-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Abs', 'Abs'), ('Arms', 'Arms'), ('Back', 'Back'), ('Calves', 'Calves'), ('Cardio', 'Cardio'), ('Chest', 'Chest'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders')], default='Abs', max_length=50)),
                ('equipment', models.CharField(choices=[('Barbell', 'Barbell'), ('Bench', 'Bench'), ('Dumbbell', 'Dumbbell'), ('Gym mat', 'Gym mat'), ('Incline bench', 'Incline bench'), ('Kettlebell', 'Kettlebell'), ('none (bodyweight exercise)', 'none (bodyweight exercise)'), ('Pull-up bar', 'Pull-up bar'), ('Swiss Ball', 'Swiss Ball'), ('SZ-Bar', 'SZ-Bar')], default='Barbell', max_length=50)),
                ('weights', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='workout date')),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('exercises', models.ManyToManyField(to='main_app.exercise')),
            ],
        ),
    ]
