# Generated by Django 4.2.5 on 2023-09-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('abs', 'Abs'), ('arms', 'Arms'), ('back', 'Back'), ('calves', 'Calves'), ('cardio', 'Cardio'), ('chest', 'Chest'), ('legs', 'Legs'), ('shoulders', 'Shoulders')], default='abs', max_length=20)),
                ('equipment', models.CharField(max_length=20)),
                ('weights', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='workout date')),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('exercises', models.ManyToManyField(related_name='workouts', to='main_app.exercise')),
            ],
        ),
    ]
