# Generated by Django 4.2.5 on 2023-09-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[(1, 'Barbell'), (8, 'Bench'), (3, 'Dumbbell'), (4, 'Gym mat'), (9, 'Incline bench'), (10, 'Kettlebell'), (7, 'none (bodyweight exercise)'), (6, 'Pull-up bar'), (5, 'Swiss Ball'), (2, 'SZ-Bar')], default=1, max_length=20),
        ),
    ]
