# Generated by Django 4.2.5 on 2023-09-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('a', 'Abs'), ('r', 'Arms'), ('b', 'Back'), ('c', 'Calves'), ('d', 'Cardio'), ('e', 'Chest'), ('l', 'Legs'), ('s', 'Shoulders')], default='a', max_length=1),
        ),
    ]
