# Generated by Django 4.2.5 on 2023-09-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_exercise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('abs', 'Abs'), ('arms', 'Arms'), ('back', 'Back'), ('calves', 'Calves'), ('cardio', 'Cardio'), ('chest', 'Chest'), ('legs', 'Legs'), ('shoulders', 'Shoulders')], default='abs', max_length=20),
        ),
    ]
