# Generated by Django 4.2.5 on 2023-09-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_exercise_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[(10, 'Abs'), (8, 'Arms'), (12, 'Back'), (14, 'Calves'), (15, 'Cardio'), (11, 'Chest'), (9, 'Legs'), (13, 'Shoulders')], default=10, max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[(10, 'Abs'), (8, 'Arms'), (12, 'Back'), (14, 'Calves'), (15, 'Cardio'), (11, 'Chest'), (9, 'Legs'), (13, 'Shoulders')], default=10, max_length=20),
        ),
    ]
